### ISSUE TITLE
FEATURE/#1 - 메인 화면 UI 프로토타입

### ISSUE THREAD

**Issue by junbangg** [TheSwiftist/TimeStacks#1]
## 설명
- 메인 화면 UI 프로토타입 구현 

## TODO
- [x] Time Stack UI 기본 구현
- [x] Time Stack 시계 애니메이션
- [x] Time Stack Swipe 애니메이션
- [ ] Time Stack 쌓는 애니메이션
