### ISSUE TITLE
FEATURE/#2 - 스택 추가 화면 UI 프로토타입

### ISSUE THREAD

**Issue by asong57** [TheSwiftist/TimeStacks#2]
## 설명
스택추가화면 UI 구현

## TODO
- [x]  추가화면 기본 UI 구성
- [ ]  데이터 추가 시 테이블뷰 업데이트 구현
- [ ] 타이머 버전, 시계 버전에 맞춰 뷰 변경
- [ ] 오늘 날짜 세팅
